### ISSUE TITLE
Clean UP & Dockerization eos1amn

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos1amn#4]

**Comment by simrantan** [comment]
The workflow is failing with this error: 
```
16:20:33 | DEBUG    | Reading from https://raw.githubusercontent.com/ersilia-os/eos1amn/main/metadata.json
Traceback (most recent call last):
  File "/home/runner/work/eos1amn/eos1amn/update_metadata_to_airtable.py", line 14, in <module>
    data = rm.read_information(org=user_name, branch=branch)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/hub/content/card.py", line 436, in read_information
    bi.from_dict(data)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/hub/content/card.py", line 371, in from_dict
    self.identifier = data["Identifier"]
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.

```
I have been looking into the code and have found the line where the error occurs and where the value that is going awry is being created, but I am still not sure why it is producing a Nonetype value. I will look into debugging this further tomorrow.

**Comment by GemmaTuron** [comment]
Hi @simrantan !

Apologies, youa re right. If a model does not have a metadata file is most likely an indicator that the model is not actually finished and was left halfway... which shouldn't happen.
@miquelduranfrigola can you confirm this model was abandoned?
Sorry about that! I'll mark this as on hold in the Git Projects and move on meanwhile

**Comment by miquelduranfrigola** [comment]
You are right. This model is part of an experimental project from a long time ago. This means it was not added through the GitHub Actions model incorporation pipeline and, therefore, it is missing a lot of stuff. I think it is a very worthy model, though.

@GemmaTuron : My suggestion would be to:

1. Open a **new model request** issue for this model. This will assign a **new** eos identifier.
2. Work on the new model, basically migrating code from eos1amn.
3. Submit the new model.
4. Delete the old repository (eos1amn) and airtable record (eos1amn) manually

It should be easy to do. What do you all think?

**Comment by GemmaTuron** [comment]
I'll close this issue and leave the model request open
